name: SE333 CI

on:
  push:
    branches: [ "main" ]   # assignment requires 'main'
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          cache: 'maven'

      # Runs Checkstyle in 'validate', then tests, then JaCoCo report
      - name: Build, Checkstyle, Test, Coverage
        run: mvn -B -Dcheckstyle.failOnViolation=false clean verify

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle.xml
          path: target/site/checkstyle.xml
          if-no-files-found: warn

      - name: Upload JaCoCo XML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco.xml
          path: target/site/jacoco/jacoco.xml
          if-no-files-found: warn